apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: surya9961/mynodeapp:v2
        ports:
        - containerPort: 3000

